//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curd_project1._1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_2
    {
        public int Employee_Id { get; set; }
        [Required(ErrorMessage ="enter the name")]
        public string Name { get; set; }
        [Required(ErrorMessage ="enter the address")]
        public string Address { get; set; }
        [Required(ErrorMessage ="enter the designation")]
        public string Designation { get; set; }
        [Range(10000,50000, ErrorMessage ="enter the salary")]
        public decimal Salary { get; set; }
        [Required(ErrorMessage ="enter the date")]
        public System.DateTime Joning_Date { get; set; }
    }
}
